### ISSUE TITLE
--no-prompt does not works as expected / documentation needs improvements

### ISSUE THREAD

**Issue by jaysee** [iandunn/wp-cli-rename-db-prefix#15]
hello,

thank for this essential plugin (why is it not a builtin?!?)

According to readme we should use `--no-prompt` to prevent any confirmation prompt, but this does not do anything

According to documentation `wp help rename-db-prefix`, we should :
```
OPTIONS

  <new_prefix>
    The new database prefix

  [--dry-run]
    Preview which data would be updated.
    default: false

  [--prompt]
    Ask for confirmation.
    default: true

  [--config-update]
    updates wp-config.php.
    default: true
```

but `--prompt` or `--prompt=false / 0 / n`, never does what it meant to do.

**Note :** `--prompt` is a builtin global feature of wp-cli that intend to prompt user for inputs, getting some more confusion on the usage of this plugin

**Comment by iandunn** [comment]
Possibly related: 54d100125b58ca14fbeb28c5647b1f1a820ec24a
