### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by szepeviktor** [iandunn/wp-cli-rename-db-prefix#6]
What do you think about `\WP_CLI::add_command( 'db change-prefix', 'WP_CLI_Rename_DB_Prefix' );` ?

**Comment by szepeviktor** [comment]
See https://github.com/iandunn/wp-cli-rename-db-prefix/blob/master/wp-cli-rename-db-prefix.php#L20

**Comment by iandunn** [comment]
I definitely think it the command should be moved under `db`, rather than being at the top-level.

I'd rather make it `wp db rename-prefix`, though, rather than `change-prefix`, to keep everything consistent.

**Comment by szepeviktor** [comment]
OK.

I have a TODO to compare my copy of iThemes Security's code with yours :)
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/wordpress-db-change-prefix.php#L9

**Comment by szepeviktor** [comment]
@iandunn Have you thought about getting this feature into WP-CLI??

**Comment by iandunn** [comment]
🤔 , my gut instinct is that it's not a common enough thing to be included in WP-CLI proper. You're welcome to open a discussion w/ the WP-CLI devs if you think they'd be interested, though.

**Comment by szepeviktor** [comment]
Thank you for your answer.
I leave it up to you.
